version: '3.4'

services:
  auth-api:
    entrypoint: ["/docker-entrypoint.sh"]
    volumes:
      - ./auth_api/src:/home/runner/:ro
  
  test-pg-db:
    container_name: test-pg-db.interconnect
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_DB: ${TEST_POSTGRES_AUTH_DB}
    ports:
      - 127.0.1.1:${TEST_POSTGRES_PORT}:${TEST_POSTGRES_PORT}
    volumes:
      - test-store-pg:/var/lib/postgresql/data
    networks:
      - interconnect

  test-cache:
    image: redis:7.0.2-alpine
    container_name: test-cache.interconnect
    restart: always
    ports:
      - 127.0.1.1:6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - test-redis-storage:/data
    networks:
      - interconnect

volumes:
  test-store-pg: 
    driver: local
  test-redis-storage: 
    driver: local